services:
    radrest.api_doc.extractor.handler:
        class: vierbergenlars\Bundle\RadRestBundle\ApiDoc\Handler\RadRestClassHandler
        arguments:
            - @service_container
        tags:
            - { name: nelmio_api_doc.extractor.handler }
    radrest.api_doc.extractor.service_handler:
        class: vierbergenlars\Bundle\RadRestBundle\ApiDoc\Handler\RadRestServiceHandler
        arguments:
            - @service_container
        tags:
            - { name: nelmio_api_doc.extractor.handler }
    radrest.pagination.adapter.knp_paginator:
        class: vierbergenlars\Bundle\RadRestBundle\Pagination\Adapters\KnpPaginationSubscriber
        tags:
            - { name: knp_paginator.subscriber }
