services:
    radrest.api_doc.extractor.handler:
        class: vierbergenlars\Bundle\RadRestBundle\ApiDoc\Handler\RadRestClassHandler
        arguments:
            - @service_container
        tags:
            - { name: nelmio_api_doc.extractor.handler }
    radrest.api_doc.extractor.service_handler:
        class: vierbergenlars\Bundle\RadRestBundle\ApiDoc\Handler\RadRestServiceHandler
        arguments:
            - @service_container
        tags:
            - { name: nelmio_api_doc.extractor.handler }
    radrest.pagination.adapter.knp_paginator:
        class: vierbergenlars\Bundle\RadRestBundle\Pagination\Adapters\KnpPaginationSubscriber
        tags:
            - { name: knp_paginator.subscriber }
    radrest.view_response_listener:
        class: vierbergenlars\Bundle\RadRestBundle\EventListener\ViewResponseListener
        arguments:
            - @fos_rest.view_handler
            - @templating
            - @logger
        tags:
            - { name: kernel.event_subscriber }
    radrest.twig.object_extension:
        class: vierbergenlars\Bundle\RadRestBundle\Twig\ObjectExtension
        tags:
            - { name: twig.extension }
