language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
env:
  - SYMFONY_VERSION=2.3.*
before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install $COMPOSER_INSTALL
script: phpunit --color $COVERAGE
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - '[[ $COVERAGE == "--coverage-clover=coverage.clover" ]] && php ocular.phar code-coverage:upload --format=php-clover coverage.clover'
matrix:
  fast_finish: true
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
  include:
    - php: 5.5
      env: COMPOSER_INSTALL=--no-dev SYMFONY_VERSION=2.3.*
    - php: 5.5
      env: SYMFONY_VERSION=2.4.* COVERAGE="--coverage-clover=coverage.clover"
    - php: 5.5
      env: SYMFONY_VERSION=2.5.*
    - php: 5.5
      env: SYMFONY_VERSION=dev-master
