language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
env:
  - COMPOSER_INSTALL=--no-dev
  - COMPOSER_INSTALL=--dev
before_script: composer install $COMPOSER_INSTALL
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  
